version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306   # Changed to avoid conflict with existing project
    container_name: laravelTaskList_mysql  # Unique container name

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080   # Changed to avoid conflict with existing project
    container_name: laravelTaskList_adminer  # Unique container name
